In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 999

In [17]:
slice_of_arr

array([999, 999, 999, 999, 999, 999])

In [18]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [24]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])

In [25]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [26]:
arr_2D[0][2]

15

In [27]:
arr{0}

SyntaxError: invalid syntax (3752943057.py, line 1)

In [28]:
arr[0]

999

In [29]:
arr_2D[0]

array([ 5, 10, 15])

In [30]:
arr_2D[1,2]

30

In [31]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2D[1][:]

array([20, 25, 30])

In [34]:
arr_2D[1:, :]

array([[20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [35]:
arr = np.arange(1,11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
bool_arr = arr > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr<3]

array([1, 2])

In [43]:
arr_2D = np.arange(50).reshape(5,10)

In [44]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2D[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
arr_2D[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [47]:
arr_2D[4,3:5]

array([43, 44])

In [48]:
arr_2D[3,5:9]

array([35, 36, 37, 38])