In [1]:
np.linspace(0,200,18)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [6]:
np.linspace(0,200,21)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140., 150., 160., 170., 180., 190., 200.])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(5)

array([0.16817604, 0.05261051, 0.11195901, 0.09620877, 0.95770313])

In [9]:
np.random.rand(10)

array([0.147587  , 0.29547297, 0.48129604, 0.54380249, 0.50963729,
       0.98422415, 0.85185932, 0.94531508, 0.68402779, 0.47864068])

In [10]:
np.random.randn(4,4)

array([[-0.16893938, -0.03752786, -0.31683395,  0.2646853 ],
       [ 0.51100461,  0.57459485, -0.96359551,  0.65554606],
       [ 0.19092868, -1.63508397,  0.0025108 , -0.81624648],
       [ 1.1678584 , -1.40017539,  1.61930227, -0.78162535]])

In [11]:
np.random.randint(1,100)

51

In [12]:
np.random.randint(1,100,10)

array([40, 45, 15, 87, 86, 12, 41, 24, 53,  1])

In [13]:
ran_array = np.random.randint(0,100,10)

In [14]:
ran_array

array([34, 82,  0, 29, 57, 99,  2, 96, 44,  3])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ran_array

array([34, 82,  0, 29, 57, 99,  2, 96, 44,  3])

In [24]:
ran_array.max()

99

In [25]:
ran_array.min()

0

In [26]:
ran_array.argmax()

5

In [28]:
arr = arr.reshape(5,5)

In [29]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.shape

(5, 5)

In [31]:
arr.dtype

dtype('int32')